# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget opencv_core opencv_flann opencv_imgproc opencv_intensity_transform opencv_ml opencv_phase_unwrapping opencv_photo opencv_plot opencv_quality opencv_reg opencv_surface_matching opencv_xphoto opencv_dnn opencv_dnn_superres opencv_fuzzy opencv_gapi opencv_hfs opencv_img_hash opencv_imgcodecs opencv_videoio opencv_highgui opencv_bioinspired opencv_dnn_objdetect opencv_features2d opencv_line_descriptor opencv_saliency opencv_text opencv_calib3d opencv_ccalib opencv_datasets opencv_objdetect opencv_rapid opencv_rgbd opencv_shape opencv_structured_light opencv_video opencv_videostab opencv_xfeatures2d opencv_ximgproc opencv_xobjdetect opencv_aruco opencv_bgsegm opencv_dpm opencv_face opencv_optflow opencv_stitching opencv_superres opencv_tracking opencv_stereo)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

set_target_properties(opencv_flann PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core"
)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

set_target_properties(opencv_imgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core"
)

# Create imported target opencv_intensity_transform
add_library(opencv_intensity_transform SHARED IMPORTED)

set_target_properties(opencv_intensity_transform PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_ml
add_library(opencv_ml SHARED IMPORTED)

set_target_properties(opencv_ml PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core"
)

# Create imported target opencv_phase_unwrapping
add_library(opencv_phase_unwrapping SHARED IMPORTED)

set_target_properties(opencv_phase_unwrapping PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_photo
add_library(opencv_photo SHARED IMPORTED)

set_target_properties(opencv_photo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_plot
add_library(opencv_plot SHARED IMPORTED)

set_target_properties(opencv_plot PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_quality
add_library(opencv_quality SHARED IMPORTED)

set_target_properties(opencv_quality PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_ml"
)

# Create imported target opencv_reg
add_library(opencv_reg SHARED IMPORTED)

set_target_properties(opencv_reg PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_surface_matching
add_library(opencv_surface_matching SHARED IMPORTED)

set_target_properties(opencv_surface_matching PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann"
)

# Create imported target opencv_xphoto
add_library(opencv_xphoto SHARED IMPORTED)

set_target_properties(opencv_xphoto PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_photo"
)

# Create imported target opencv_dnn
add_library(opencv_dnn SHARED IMPORTED)

set_target_properties(opencv_dnn PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_dnn_superres
add_library(opencv_dnn_superres SHARED IMPORTED)

set_target_properties(opencv_dnn_superres PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_ml;opencv_quality;opencv_dnn"
)

# Create imported target opencv_fuzzy
add_library(opencv_fuzzy SHARED IMPORTED)

set_target_properties(opencv_fuzzy PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_gapi
add_library(opencv_gapi SHARED IMPORTED)

set_target_properties(opencv_gapi PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_hfs
add_library(opencv_hfs SHARED IMPORTED)

set_target_properties(opencv_hfs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_img_hash
add_library(opencv_img_hash SHARED IMPORTED)

set_target_properties(opencv_img_hash PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

set_target_properties(opencv_imgcodecs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc"
)

# Create imported target opencv_videoio
add_library(opencv_videoio SHARED IMPORTED)

set_target_properties(opencv_videoio PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_imgcodecs"
)

# Create imported target opencv_highgui
add_library(opencv_highgui SHARED IMPORTED)

set_target_properties(opencv_highgui PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
)

# Create imported target opencv_bioinspired
add_library(opencv_bioinspired SHARED IMPORTED)

set_target_properties(opencv_bioinspired PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_dnn_objdetect
add_library(opencv_dnn_objdetect SHARED IMPORTED)

set_target_properties(opencv_dnn_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_imgproc;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_features2d
add_library(opencv_features2d SHARED IMPORTED)

set_target_properties(opencv_features2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_line_descriptor
add_library(opencv_line_descriptor SHARED IMPORTED)

set_target_properties(opencv_line_descriptor PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
)

# Create imported target opencv_saliency
add_library(opencv_saliency SHARED IMPORTED)

set_target_properties(opencv_saliency PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
)

# Create imported target opencv_text
add_library(opencv_text SHARED IMPORTED)

set_target_properties(opencv_text PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
)

# Create imported target opencv_calib3d
add_library(opencv_calib3d SHARED IMPORTED)

set_target_properties(opencv_calib3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
)

# Create imported target opencv_ccalib
add_library(opencv_ccalib SHARED IMPORTED)

set_target_properties(opencv_ccalib PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_datasets
add_library(opencv_datasets SHARED IMPORTED)

set_target_properties(opencv_datasets PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_text"
)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

set_target_properties(opencv_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_rapid
add_library(opencv_rapid SHARED IMPORTED)

set_target_properties(opencv_rapid PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_rgbd
add_library(opencv_rgbd SHARED IMPORTED)

set_target_properties(opencv_rgbd PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_shape
add_library(opencv_shape SHARED IMPORTED)

set_target_properties(opencv_shape PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_structured_light
add_library(opencv_structured_light SHARED IMPORTED)

set_target_properties(opencv_structured_light PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_phase_unwrapping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_video
add_library(opencv_video SHARED IMPORTED)

set_target_properties(opencv_video PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_videostab
add_library(opencv_videostab SHARED IMPORTED)

set_target_properties(opencv_videostab PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_photo;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_video"
)

# Create imported target opencv_xfeatures2d
add_library(opencv_xfeatures2d SHARED IMPORTED)

set_target_properties(opencv_xfeatures2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_shape"
)

# Create imported target opencv_ximgproc
add_library(opencv_ximgproc SHARED IMPORTED)

set_target_properties(opencv_ximgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_video"
)

# Create imported target opencv_xobjdetect
add_library(opencv_xobjdetect SHARED IMPORTED)

set_target_properties(opencv_xobjdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_objdetect"
)

# Create imported target opencv_aruco
add_library(opencv_aruco SHARED IMPORTED)

set_target_properties(opencv_aruco PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
)

# Create imported target opencv_bgsegm
add_library(opencv_bgsegm SHARED IMPORTED)

set_target_properties(opencv_bgsegm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_video"
)

# Create imported target opencv_dpm
add_library(opencv_dpm SHARED IMPORTED)

set_target_properties(opencv_dpm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_objdetect"
)

# Create imported target opencv_face
add_library(opencv_face SHARED IMPORTED)

set_target_properties(opencv_face PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_photo;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_objdetect"
)

# Create imported target opencv_optflow
add_library(opencv_optflow SHARED IMPORTED)

set_target_properties(opencv_optflow PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_video;opencv_ximgproc"
)

# Create imported target opencv_stitching
add_library(opencv_stitching SHARED IMPORTED)

set_target_properties(opencv_stitching PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_shape;opencv_xfeatures2d"
)

# Create imported target opencv_superres
add_library(opencv_superres SHARED IMPORTED)

set_target_properties(opencv_superres PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_video;opencv_ximgproc;opencv_optflow"
)

# Create imported target opencv_tracking
add_library(opencv_tracking SHARED IMPORTED)

set_target_properties(opencv_tracking PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_plot;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_text;opencv_calib3d;opencv_datasets;opencv_video"
)

# Create imported target opencv_stereo
add_library(opencv_stereo SHARED IMPORTED)

set_target_properties(opencv_stereo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_plot;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_text;opencv_calib3d;opencv_datasets;opencv_video;opencv_tracking"
)

# Import target "opencv_core" for configuration "Debug"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_core410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_core410d.dll"
  )

# Import target "opencv_flann" for configuration "Debug"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_flann410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_flann410d.dll"
  )

# Import target "opencv_imgproc" for configuration "Debug"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_imgproc410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_imgproc410d.dll"
  )

# Import target "opencv_intensity_transform" for configuration "Debug"
set_property(TARGET opencv_intensity_transform APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_intensity_transform PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_intensity_transform410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_intensity_transform410d.dll"
  )

# Import target "opencv_ml" for configuration "Debug"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_ml410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_ml410d.dll"
  )

# Import target "opencv_phase_unwrapping" for configuration "Debug"
set_property(TARGET opencv_phase_unwrapping APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_phase_unwrapping PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_phase_unwrapping410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_phase_unwrapping410d.dll"
  )

# Import target "opencv_photo" for configuration "Debug"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_photo410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_photo410d.dll"
  )

# Import target "opencv_plot" for configuration "Debug"
set_property(TARGET opencv_plot APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_plot PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_plot410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_plot410d.dll"
  )

# Import target "opencv_quality" for configuration "Debug"
set_property(TARGET opencv_quality APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_quality PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_quality410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_quality410d.dll"
  )

# Import target "opencv_reg" for configuration "Debug"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_reg410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_reg410d.dll"
  )

# Import target "opencv_surface_matching" for configuration "Debug"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_surface_matching410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_surface_matching410d.dll"
  )

# Import target "opencv_xphoto" for configuration "Debug"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_xphoto410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_xphoto410d.dll"
  )

# Import target "opencv_dnn" for configuration "Debug"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_dnn410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_dnn410d.dll"
  )

# Import target "opencv_dnn_superres" for configuration "Debug"
set_property(TARGET opencv_dnn_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn_superres PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_dnn_superres410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_dnn_superres410d.dll"
  )

# Import target "opencv_fuzzy" for configuration "Debug"
set_property(TARGET opencv_fuzzy APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_fuzzy PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_fuzzy410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_fuzzy410d.dll"
  )

# Import target "opencv_gapi" for configuration "Debug"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_gapi410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_gapi410d.dll"
  )

# Import target "opencv_hfs" for configuration "Debug"
set_property(TARGET opencv_hfs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_hfs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_hfs410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_hfs410d.dll"
  )

# Import target "opencv_img_hash" for configuration "Debug"
set_property(TARGET opencv_img_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_img_hash PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_img_hash410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_img_hash410d.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Debug"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_imgcodecs410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_imgcodecs410d.dll"
  )

# Import target "opencv_videoio" for configuration "Debug"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_videoio410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_videoio410d.dll"
  )

# Import target "opencv_highgui" for configuration "Debug"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_highgui410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_highgui410d.dll"
  )

# Import target "opencv_bioinspired" for configuration "Debug"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_bioinspired410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_bioinspired410d.dll"
  )

# Import target "opencv_dnn_objdetect" for configuration "Debug"
set_property(TARGET opencv_dnn_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dnn_objdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_dnn_objdetect410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_dnn_objdetect410d.dll"
  )

# Import target "opencv_features2d" for configuration "Debug"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_features2d410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_features2d410d.dll"
  )

# Import target "opencv_line_descriptor" for configuration "Debug"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_line_descriptor410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_line_descriptor410d.dll"
  )

# Import target "opencv_saliency" for configuration "Debug"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_saliency410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_saliency410d.dll"
  )

# Import target "opencv_text" for configuration "Debug"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_text410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_text410d.dll"
  )

# Import target "opencv_calib3d" for configuration "Debug"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_calib3d410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_calib3d410d.dll"
  )

# Import target "opencv_ccalib" for configuration "Debug"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_ccalib410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_ccalib410d.dll"
  )

# Import target "opencv_datasets" for configuration "Debug"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_datasets410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_datasets410d.dll"
  )

# Import target "opencv_objdetect" for configuration "Debug"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_objdetect410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_objdetect410d.dll"
  )

# Import target "opencv_rapid" for configuration "Debug"
set_property(TARGET opencv_rapid APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_rapid PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_rapid410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_rapid410d.dll"
  )

# Import target "opencv_rgbd" for configuration "Debug"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_rgbd410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_rgbd410d.dll"
  )

# Import target "opencv_shape" for configuration "Debug"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_shape410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_shape410d.dll"
  )

# Import target "opencv_structured_light" for configuration "Debug"
set_property(TARGET opencv_structured_light APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_structured_light PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_structured_light410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_structured_light410d.dll"
  )

# Import target "opencv_video" for configuration "Debug"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_video410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_video410d.dll"
  )

# Import target "opencv_videostab" for configuration "Debug"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_videostab410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_videostab410d.dll"
  )

# Import target "opencv_xfeatures2d" for configuration "Debug"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_xfeatures2d410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_xfeatures2d410d.dll"
  )

# Import target "opencv_ximgproc" for configuration "Debug"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_ximgproc410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_ximgproc410d.dll"
  )

# Import target "opencv_xobjdetect" for configuration "Debug"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_xobjdetect410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_xobjdetect410d.dll"
  )

# Import target "opencv_aruco" for configuration "Debug"
set_property(TARGET opencv_aruco APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_aruco PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_aruco410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_aruco410d.dll"
  )

# Import target "opencv_bgsegm" for configuration "Debug"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_bgsegm410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_bgsegm410d.dll"
  )

# Import target "opencv_dpm" for configuration "Debug"
set_property(TARGET opencv_dpm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_dpm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_dpm410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_dpm410d.dll"
  )

# Import target "opencv_face" for configuration "Debug"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_face410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_face410d.dll"
  )

# Import target "opencv_optflow" for configuration "Debug"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_optflow410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_optflow410d.dll"
  )

# Import target "opencv_stitching" for configuration "Debug"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_stitching410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_stitching410d.dll"
  )

# Import target "opencv_superres" for configuration "Debug"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_superres410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_superres410d.dll"
  )

# Import target "opencv_tracking" for configuration "Debug"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_tracking410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_tracking410d.dll"
  )

# Import target "opencv_stereo" for configuration "Debug"
set_property(TARGET opencv_stereo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_stereo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/My_file/opencv4.1/opencv-bulild/lib/Debug/opencv_stereo410d.lib"
  IMPORTED_LOCATION_DEBUG "D:/My_file/opencv4.1/opencv-bulild/bin/Debug/opencv_stereo410d.dll"
  )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_core410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_core410.dll"
  )

# Import target "opencv_flann" for configuration "Release"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_flann410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_flann410.dll"
  )

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_imgproc410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_imgproc410.dll"
  )

# Import target "opencv_intensity_transform" for configuration "Release"
set_property(TARGET opencv_intensity_transform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_intensity_transform PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_intensity_transform410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_intensity_transform410.dll"
  )

# Import target "opencv_ml" for configuration "Release"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_ml410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_ml410.dll"
  )

# Import target "opencv_phase_unwrapping" for configuration "Release"
set_property(TARGET opencv_phase_unwrapping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_phase_unwrapping PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_phase_unwrapping410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_phase_unwrapping410.dll"
  )

# Import target "opencv_photo" for configuration "Release"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_photo410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_photo410.dll"
  )

# Import target "opencv_plot" for configuration "Release"
set_property(TARGET opencv_plot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_plot PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_plot410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_plot410.dll"
  )

# Import target "opencv_quality" for configuration "Release"
set_property(TARGET opencv_quality APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_quality PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_quality410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_quality410.dll"
  )

# Import target "opencv_reg" for configuration "Release"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_reg410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_reg410.dll"
  )

# Import target "opencv_surface_matching" for configuration "Release"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_surface_matching410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_surface_matching410.dll"
  )

# Import target "opencv_xphoto" for configuration "Release"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_xphoto410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_xphoto410.dll"
  )

# Import target "opencv_dnn" for configuration "Release"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_dnn410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_dnn410.dll"
  )

# Import target "opencv_dnn_superres" for configuration "Release"
set_property(TARGET opencv_dnn_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn_superres PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_dnn_superres410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_dnn_superres410.dll"
  )

# Import target "opencv_fuzzy" for configuration "Release"
set_property(TARGET opencv_fuzzy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_fuzzy PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_fuzzy410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_fuzzy410.dll"
  )

# Import target "opencv_gapi" for configuration "Release"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_gapi410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_gapi410.dll"
  )

# Import target "opencv_hfs" for configuration "Release"
set_property(TARGET opencv_hfs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_hfs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_hfs410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_hfs410.dll"
  )

# Import target "opencv_img_hash" for configuration "Release"
set_property(TARGET opencv_img_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_img_hash PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_img_hash410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_img_hash410.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Release"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_imgcodecs410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_imgcodecs410.dll"
  )

# Import target "opencv_videoio" for configuration "Release"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_videoio410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_videoio410.dll"
  )

# Import target "opencv_highgui" for configuration "Release"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_highgui410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_highgui410.dll"
  )

# Import target "opencv_bioinspired" for configuration "Release"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_bioinspired410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_bioinspired410.dll"
  )

# Import target "opencv_dnn_objdetect" for configuration "Release"
set_property(TARGET opencv_dnn_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_dnn_objdetect410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_dnn_objdetect410.dll"
  )

# Import target "opencv_features2d" for configuration "Release"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_features2d410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_features2d410.dll"
  )

# Import target "opencv_line_descriptor" for configuration "Release"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_line_descriptor410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_line_descriptor410.dll"
  )

# Import target "opencv_saliency" for configuration "Release"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_saliency410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_saliency410.dll"
  )

# Import target "opencv_text" for configuration "Release"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_text410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_text410.dll"
  )

# Import target "opencv_calib3d" for configuration "Release"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_calib3d410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_calib3d410.dll"
  )

# Import target "opencv_ccalib" for configuration "Release"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_ccalib410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_ccalib410.dll"
  )

# Import target "opencv_datasets" for configuration "Release"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_datasets410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_datasets410.dll"
  )

# Import target "opencv_objdetect" for configuration "Release"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_objdetect410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_objdetect410.dll"
  )

# Import target "opencv_rapid" for configuration "Release"
set_property(TARGET opencv_rapid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rapid PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_rapid410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_rapid410.dll"
  )

# Import target "opencv_rgbd" for configuration "Release"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_rgbd410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_rgbd410.dll"
  )

# Import target "opencv_shape" for configuration "Release"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_shape410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_shape410.dll"
  )

# Import target "opencv_structured_light" for configuration "Release"
set_property(TARGET opencv_structured_light APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_structured_light PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_structured_light410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_structured_light410.dll"
  )

# Import target "opencv_video" for configuration "Release"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_video410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_video410.dll"
  )

# Import target "opencv_videostab" for configuration "Release"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_videostab410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_videostab410.dll"
  )

# Import target "opencv_xfeatures2d" for configuration "Release"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_xfeatures2d410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_xfeatures2d410.dll"
  )

# Import target "opencv_ximgproc" for configuration "Release"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_ximgproc410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_ximgproc410.dll"
  )

# Import target "opencv_xobjdetect" for configuration "Release"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_xobjdetect410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_xobjdetect410.dll"
  )

# Import target "opencv_aruco" for configuration "Release"
set_property(TARGET opencv_aruco APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_aruco PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_aruco410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_aruco410.dll"
  )

# Import target "opencv_bgsegm" for configuration "Release"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_bgsegm410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_bgsegm410.dll"
  )

# Import target "opencv_dpm" for configuration "Release"
set_property(TARGET opencv_dpm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dpm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_dpm410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_dpm410.dll"
  )

# Import target "opencv_face" for configuration "Release"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_face410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_face410.dll"
  )

# Import target "opencv_optflow" for configuration "Release"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_optflow410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_optflow410.dll"
  )

# Import target "opencv_stitching" for configuration "Release"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_stitching410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_stitching410.dll"
  )

# Import target "opencv_superres" for configuration "Release"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_superres410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_superres410.dll"
  )

# Import target "opencv_tracking" for configuration "Release"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_tracking410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_tracking410.dll"
  )

# Import target "opencv_stereo" for configuration "Release"
set_property(TARGET opencv_stereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stereo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/My_file/opencv4.1/opencv-bulild/lib/Release/opencv_stereo410.lib"
  IMPORTED_LOCATION_RELEASE "D:/My_file/opencv4.1/opencv-bulild/bin/Release/opencv_stereo410.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
